# Generated by Django 3.0.6 on 2020-06-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_page', '0002_environmentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_CrimeData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.FloatField()),
                ('pharmacy', models.FloatField()),
                ('sickbed', models.FloatField()),
                ('crime_occ', models.FloatField()),
                ('crime_arr', models.FloatField()),
                ('gu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_page.Goo')),
            ],
        ),
    ]
