# Generated by Django 3.0.6 on 2020-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_info',
            fields=[
                ('loc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kor_loc', models.CharField(max_length=50)),
                ('longi', models.DecimalField(decimal_places=15, max_digits=30)),
                ('lati', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
