# Generated by Django 3.0.6 on 2020-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
