# Generated by Django 3.0.6 on 2020-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('current_residence', models.CharField(max_length=100)),
                ('preferred_residence', models.CharField(max_length=100)),
                ('admin_whether', models.CharField(max_length=1)),
            ],
        ),
    ]
