# Generated by Django 3.0.6 on 2020-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admin_whether',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_residence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_residence',
            field=models.CharField(default='', max_length=100),
        ),
    ]
